### ISSUE TITLE
Classpath based ruleset resolution

### ISSUE THREAD

**Issue by shimikano** [acanda/eclipse-pmd#27]
Hello

Is it currently possible to reference a `ruleset.xml` file that resides in the *classpath* of the target project?

E.g., some `rulset.xml` file that is shipped with a maven dependency that the project depends upon?

This would help us centralize the rule sets, since our maven PMD analysis runs are based on such "classpath based rulesets".

What do you think?

Thanks a lot.

**Comment by acanda** [comment]
It's currently not possible to to reference a `ruleset.xml` that resides in the classpath.

However, if the source of your PMD maven module is in a SCM which exposes its files over http you can use a remote rule set configuration which references a rules via an URL. Since the URL can be anything Java can resolve it is also possible to use the [jar protocol](https://docs.oracle.com/javase/7/docs/api/java/net/JarURLConnection.html). This way you might be able to reference your `ruleset.xml` if it resides in a jar file (which maven modules usually are).

I've never come across this kind of setup. Could you tell me why you do it this way? It might very well be that I add this kind of rule set reference in a future version.

**Comment by shimikano** [comment]
Thanks a lot for your feedback!

Basically, in an experimental fashion, we put our global `ruleset.xml` in a jar artifact and reference it like this in the `pom.xml` of a project:
```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-pmd-plugin</artifactId>
  <configuration>
    <rulesets>
      <ruleset>path/to/ruleset.xml</ruleset> <!-- in the classpath -->
    </rulesets>
  </configuration>
  <dependencies>
    <dependency>
      <!-- the jar artifact containing the ruleset -->
    </dependency>
  </dependencies>
</plugin>
```
But come to think of it, an HTTP access to the SCM - as you suggest - seems much more straight-forward and easy to integrate. So, we're gonna try going down that road and you might as well close this issue.

BTW, thanks for your plugin. We think that the integration and overall user experience is superior to the official PMD plugin.

**Comment by acanda** [comment]
It's one of my goals to have a single source of truth for the rule set file so you can use the same file wherever you run PMD (Eclipse, Maven, ...). I'm always interested to learn how other teams are using PMD and if eclipse-pmd is standing in the way of having a single file for everything then I'm happy to resolve the issue.

I'm glad to hear you like eclipse-pmd, especially since integration and user experience of the official plugin are two of the main reasons I wrote the plugin.
