### ISSUE TITLE
Eclipse update site is not available

### ISSUE THREAD

**Issue by bryanschofield** [acanda/eclipse-pmd#30]
Eclipse update site is not available: http://www.acanda.ch/eclipse-pmd/release/latest

    Forbidden
    You do not have permission to access this document.

    Web Server at test.skeleton 

http://www.acanda.ch simply displays a single | character

**Comment by acanda** [comment]
Please have a look at issue #26. Does this help with your problem?

**Comment by bryanschofield** [comment]
No luck.
I do have to access the internet using a corporate proxy.
Proxy is configured correctly, every other plugin I've installed has worked fine.
I am able to download the artifacts.jar by hand.

**Comment by acanda** [comment]
Are you trying to install the plugin using the marketplace integrated in Eclipse (`Help` > `Eclipse Marketplace...`), via drag&drop from the website or do you directly enter the update site URL (`Help` -> `Install New Software...`)?

**Comment by bryanschofield** [comment]
I've tried both methods

**Comment by acanda** [comment]
Could you check if the Eclipse log file gives any hints at why it's not working? You'll find it at `[your-workspace]/.metadata/.log`.

**Comment by bryanschofield** [comment]
Eclipse appears to be able to access the content.jar, but fails to read .../release/latest

    Server returned lastModified <= 0 for http://www.acanda.ch/eclipse-pmd/release/latest/content.jar
    Unable to read repository at http://www.acanda.ch/eclipse-pmd/release/latest.

**Comment by acanda** [comment]
Which version of Eclipse are you using?

**Comment by bryanschofield** [comment]
Version: Mars Release (4.5.0)
Build id: 20150621-1200

**Comment by bryanschofield** [comment]
I just noticed this page: https://github.com/acanda/eclipse-pmd/releases
I'll install it by hand!

**Comment by acanda** [comment]
It's hard to tell what the problem is since I can't reproduce it. The only thing I currently can come up with is that something went wrong the first time your proxy tried to download content.jar resulting in a corrupt file which is now cached in your proxy.

You could try the update site `http://www.acanda.ch/eclipse-pmd/release/1.6`. This is the exact same thing as `http://www.acanda.ch/eclipse-pmd/release/latest` but under a different URL. This would force your proxy to download the files again.
