### ISSUE TITLE
PMD analyzes files located outside of the source directories

### ISSUE THREAD

**Issue by phcouton** [acanda/eclipse-pmd#34]
I a have a lot of project having directories containing java files, but these directories are not configured in Eclipse to be source directories for the project. So, the files in these directories are not compiled (and sometimes these files does not compile at all).

However, PMD analyzes theses files anyway, giving several hundred of warnings for things which must be ignored.

**Comment by acanda** [comment]
The plug-in cannot ignore the files outside of the source directories by default as PMD can also analyse files that are typically not in source directories (e.g. xml files). You can however make eclipse-pmd ignore those files by [excluding them in your rule set configuration](https://pmd.github.io/pmd-5.4.1/customizing/howtomakearuleset.html#Excluding_files_from_a_ruleset).

**Comment by phcouton** [comment]
I didn't known this possibility, thanks for the hint :) That said, it is not as easy as it seems to use it.

Let me explain:
* we have only one ruleset, which is shared between many projets and shared between many developpers.
* my first idea was to, in an Eclipse project, use two rulesets: the shared one and a one local to the project for the exclusions: it does not work. I think that there is a kind of OR between the two rulesets, so the exclusions are "overriden" by the shared rulet and not taken in account. I don't know if this problem come from PMD or Eclipse-PMD.
* The second idea was to use only a ruleset specific to a project with the exclusions and which "includes" the shared rulesets, using a <rule ref="..." />. This solutions works partly: the shared rules are used and the exclusions are taken in account. However, the ref attributes must use absolute paths, and so this solution can't be shared between developpers working on different OS :(

Is there any other way to do?

**Comment by acanda** [comment]
The idea behind eclipse-pmd is that you use the same configuration for everything (IDE, build tool, CI) so you don't have any "it worked on my machine" moments.

Your first idea won't work because there is an OR between the two ruleset (as you correctly guessed).

Your second idea however might work if you put an URL into the `href` attribute. I'm not sure if a relative `file:` URL would work but if your shared ruleset is committed and your code repository exposes those files it might work with the URL to the ruleset file in the repository.
All this is parsed and evaluated by PMD, not eclipse-pmd. If you want to be able to use relative file path in the `href`attribute (which I think is very reasonable) then you have to [create a feature request](http://sourceforge.net/p/pmd/feature-requests/) with PMD.

You might find another solution as well by looking at PMD's source code: [RuleSetReferenceId](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/RuleSetReferenceId.java#L129) parses the content of the `href` attribute.

**Comment by phcouton** [comment]
It works for me with the `ref` attribute, and it is good to see that it works with every tool. So, I will close this ticket.

I didn't checked with a relative file path, no news to add on this subject...
