### ISSUE TITLE
Diff to pmd/pmd-eclipse-plugin

### ISSUE THREAD

**Issue by vorburger** [acanda/eclipse-pmd#38]
Hoi (Salut?),

Upon searching around where to [file some bug](for https://sourceforge.net/p/pmd/bugs/1503/) in the "PMD Eclipse plugin", I just realized that there are two different ones, this VS https://github.com/pmd/pmd-eclipse-plugin!  I would not have thought that this world is big enough for two people writing separate Eclipse plugins for a code quality tool ... ;-)

Would you perhaps like to add section to your README and/or [the homepage](http://acanda.github.io/eclipse-pmd/) to outline how this one differs from pmd/pmd-eclipse-plugin ?

Specifically, do you happen to have CPD integration, with a Builder? As far as I could see pmd/pmd-eclipse-plugin does not (one seems to have to explicitly right-click PMD > Find Suspect Code And Paste with it, whereas a native on Save CPD validation be cool, of course. (I realize the possible performance impact, because it would have to look at more than just the changed resource?)

BTW: Do you know about https://github.com/m2e-code-quality/m2e-code-quality ? Perhaps you'd like to contribute eclipse-pmd support to that?  Note also https://github.com/m2e-code-quality/m2e-code-quality/issues/93.

Full disclosure: I'm trying to understand if https://github.com/vorburger/opendaylight-eclipse-setup would be best served by switching from pmd/pmd-eclipse-plugin to eclipse-pmd ... ;-)

Grüssli,
M.

**Comment by acanda** [comment]
Hi Michael!

I started eclipse-pmd a couple of years ago because I wanted a PMD Plugin that was easy to use for development teams and "PMD Eclipse Plugin" made it quite hard to keep the PMD configuration in sync within a team (I don't know if that is still the case since I haven't used the "PMD Eclipse Plugin" for years). 

I designed eclipse-pmd so it is really easy to have only a single source for the PMD rule set(s). If you put the rule set file into your code repository you can share it with your whole team and changes are picked up by the plugin automatically. And since its the same file format that PMD uses, the same rule set file can be used for the build (Maven, Gradle etc.) and on you CI server.

I also wanted the plugin to be out of your way as much as possible. A developer should not have to remember to run PMD when writing code - the plugin should do it automatically. So I designed eclipse-pmd in a way that once you point it to your rule set file you don't have to do anything else. It will analyse a file when you save and give you feedback immediately so you can fix the issues right when you introduced them.

eclipse-pmd also offers quite a few quick-fixes for the issues PMD finds. This helps a lot when you start using PMD on an already existing project. It also shows less experienced developers how to fix those issues.

As for CPD: eclipse-pmd does not support it (yet). It won't run CPD automatically and you also can't run it manually. It's not because I don't like CPD, it's just a result of my limited time. Although I'm not sure if CPD is the right tool to find duplicated code for Eclipse. As far as I know CPD can only analyse the whole code base at once and not incrementally. This makes it difficult to analyse the code while you write it. I quite like the way IntelliJ IDEA works: as soon as you have written (or copy/pasted) a piece of code it lets you know that this code is duplicated. This will probably only be possible if we could analyse the code incrementally.

I know of m2e-code-quality and would like to see it use eclipse-pmd. Unfortunately I have already enough to do with eclipse-pmd itself. But if you want m2e-code-quality to use eclipse-pmd (or at least offer it as an option) then you should open a new issue at their project. Maybe someone else will pick it up. 
 
And finally, in my totally unbiased opinion: you should definitely switch your project from pmd-eclipse-plugin to eclipse-pmd ;-)

**Comment by vorburger** [comment]
> If you put the rule set file into your code repository you can share it with your whole team and changes are picked up by the plugin automatically.

How do you find the configuration? In a big project with many modules (i.e. Maven projects), just checking in the root of the respective Eclipse projects isn't viable, and you have to be able to share such configurations somehow. Maven parent pom.xml are one way to do this in a big code base of course.

> eclipse-pmd also offers quite a few quick-fixes for the issues PMD finds.

That's nice!

> I know of m2e-code-quality and would like to see it use eclipse-pmd. Unfortunately I have already enough to do with eclipse-pmd itself. But if you want m2e-code-quality to use eclipse-pmd (or at least offer it as an option) then you should open a new issue at their project. 

Sure...  https://github.com/m2e-code-quality/m2e-code-quality/issues/96 ;-)

**Comment by acanda** [comment]
Regarding the configuration, I usually put it in the same place as the parent pom. In a simple single pom project I put it in a config folder. But you are free to put it wherever you think it fits best as eclipse-pmd can be configured accordingly.
