### ISSUE TITLE
Improve ruleset feedback

### ISSUE THREAD

**Issue by malnormalulo** [acanda/eclipse-pmd#39]
AddRuleSetConfigurationModel.validateLocation() gags all exceptions when parsing the ruleset and simply displays the static message "The rule set configuration at the given location is invalid". It would be helpful if it gave some indication of what the problem was.

**Comment by acanda** [comment]
Good point. I'll see what I can do.

**Comment by acanda** [comment]
After looking into the issue I found that the static message is probably the best that can be done. The problem is that I let PMD parse the configuration file and either get a RuleSet if it was valid or an Exception if it was invalid. The Exception can be anything from a NullPointer to an ArrayIndexOutOfBoundException or any of the many exception you can get from the XML parser.

Just displaying the exception message in the dialog does not help in most cases as you would need the whole stack trace to figure out what's wrong.

So I'm leaving the static message but log the exception into the error log. This way you can at least open the "Error Log" view and examine the entire stack trace.
