### ISSUE TITLE
New releases

### ISSUE THREAD

**Issue by lukedirtwalker** [acanda/eclipse-pmd#51]
Hi,

Great Plugin. I saw that the last release was at the end of 2015 with PMD 5.4.1.
But in the git history you updated to newer PMD versions.
Is there any reason why you don't do any releases anymore?

Cheers,
Lukas

**Comment by acanda** [comment]
Hi Lukas

Updating the version number of PMD is the easy task – testing if it still works is a different issue. I learned that even if all the automated unit and integration tests work, using the plugin in a real life environment with a lot of other plugins can lead to unpredictable problems. I usually tested a new version by using it myself for a week or so at work.

At the end of 2015 I switched from Eclipse to Intellij IDEA which made testing the plugin in real world environments much harder and much more time consuming. I still want to do releases but I also want to make sure the plugin works and I simply didn’t find the time to do the real world testing. This is the main reason why there hasn’t been a release since end of 2015.

**Would you like to help?** If you use Java, Eclipse and eclipse-pmd every day at work I can set up a beta update site which would allow you to install the latest version. All you have to do is use it for a week and let me know if any problems pop up. If everything works then I could make the long overdue release.

**Comment by lukedirtwalker** [comment]
Hi,

Sure I would love to try it out. I use Java and eclipse-pmd everyday.
Thanks a lot for your suggestion.

Cheers,
Lukas

**Comment by acanda** [comment]
Thanks for your help. I opened a new issue for testing the release 1.9: #52
